### ISSUE TITLE
Add HTML string analysis

### ISSUE THREAD

**Issue by ANK1036Official** [Kel0/pywappalyzer#8]
Was thinking it might be useful to some for you to make it possible to read pure HTML code from a variable for analysis.

Like getting the contents of a HTML file, or from requests, and then passing that as a variable to pywappalyzer.

Think you could implement that?

**Comment by Kel0** [comment]
Implemented https://github.com/Kel0/pywappalyzer/commit/edee453b5049a8eeba862f9962d40db798211249
